### ISSUE TITLE
TITLE: Create TODO

### ISSUE THREAD

**Issue by ZackSoucek** [carsonpepe/TODO_App#3]
DESCRIPTION:
Users should be able to add todos to the backend, which should be non-volatile. This functionality should be reflected with a frontend menu that users can interact with to fill out fields for their TODO item.

REQUIREMENTS:
- users can add todos
- '+' button pulls up the frontend representation of adding a TODO item
- TODOs persist over page refresh
EST. TIME (in hours): 4

**Comment by carsonpepe** [comment]
Forgot to link my branch to this, but I completed the front end for this already - closing this work item
